# docker compose -p launchpad-local-postgis up -d

services:
  postgis:
    image: postgis/postgis:15-3.5-alpine
    container_name: launchpad-postgis-local
    restart: unless-stopped
    ports:
      - "1299:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - launchpad-database-local-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: launchpad-postgis-metrics-local
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@postgis:5432?sslmode=disable"

volumes:
  launchpad-database-local-data:
    name: launchpad-database-local-data