// <auto-generated />
using System;
using Launchpad.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Launchpad.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317160916_AddedEmployeeProjects")]
    partial class AddedEmployeeProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Среднее"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Среднее специальное"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Неоконченное высшее"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Высшее"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Бакалавр"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Магистр"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Доктор наук"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletionYear")
                        .HasColumnType("integer");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EducationProjects");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EducationLevel_EmployeeEducations");

                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeEducations");

                    b.Navigation("EducationLevel");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeProjects");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("EmployeeEducations");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeEducations");

                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
