// <auto-generated />
using System;
using Launchpad.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Launchpad.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320200431_FixedEmployerVerificationResponseType")]
    partial class FixedEmployerVerificationResponseType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityFieldEmployer", b =>
                {
                    b.Property<int>("ActivityFieldsId")
                        .HasColumnType("integer");

                    b.Property<long>("EmployersId")
                        .HasColumnType("bigint");

                    b.HasKey("ActivityFieldsId", "EmployersId");

                    b.HasIndex("EmployersId");

                    b.ToTable("ActivityField_Employer_Map", (string)null);
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.Property<long>("EmployeesId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("EmployeeSkillMap", (string)null);
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.ActivityField", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityFieldGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityFieldGroupId");

                    b.ToTable("ActivityFields");

                    b.HasData(
                        new
                        {
                            Id = -1901,
                            ActivityFieldGroupId = -19,
                            Title = "Автозапчасти, шины (розничная торговля)"
                        },
                        new
                        {
                            Id = -1902,
                            ActivityFieldGroupId = -19,
                            Title = "Автокомпоненты, запчасти (производство)"
                        },
                        new
                        {
                            Id = -1903,
                            ActivityFieldGroupId = -19,
                            Title = "Автокомпоненты, запчасти, шины (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1904,
                            ActivityFieldGroupId = -19,
                            Title = "Легковые, грузовые автомобили, мототехника, автобусы, троллейбусы (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1905,
                            ActivityFieldGroupId = -19,
                            Title = "Легковые, грузовые автомобили, мототехника, автобусы, троллейбусы (производство)"
                        },
                        new
                        {
                            Id = -1906,
                            ActivityFieldGroupId = -19,
                            Title = "Розничная торговля автомобилями (дилерский центр)"
                        },
                        new
                        {
                            Id = -1907,
                            ActivityFieldGroupId = -19,
                            Title = "Техническое обслуживание, ремонт автомобилей"
                        },
                        new
                        {
                            Id = -1908,
                            ActivityFieldGroupId = -19,
                            Title = "Финансовые услуги (кэптивные банки и лизинговые компании)"
                        },
                        new
                        {
                            Id = -101,
                            ActivityFieldGroupId = -1,
                            Title = "Гостиница"
                        },
                        new
                        {
                            Id = -102,
                            ActivityFieldGroupId = -1,
                            Title = "Кейтеринг (выездное обслуживание)"
                        },
                        new
                        {
                            Id = -103,
                            ActivityFieldGroupId = -1,
                            Title = "Ресторан, общественное питание, фаст-фуд"
                        },
                        new
                        {
                            Id = -201,
                            ActivityFieldGroupId = -2,
                            Title = "Государственные организации"
                        },
                        new
                        {
                            Id = -301,
                            ActivityFieldGroupId = -3,
                            Title = "Добыча и обогащение минерального сырья (соль, сера, глинозем), разработка карьеров (песок, глина, камень), добыча торфа"
                        },
                        new
                        {
                            Id = -302,
                            ActivityFieldGroupId = -3,
                            Title = "Добыча и обогащение руд черных, цветных, драгоценных, благородных, редких металлов"
                        },
                        new
                        {
                            Id = -303,
                            ActivityFieldGroupId = -3,
                            Title = "Добыча и обогащение угля"
                        },
                        new
                        {
                            Id = -304,
                            ActivityFieldGroupId = -3,
                            Title = "Инженерно-изыскательские, гидрогеологические, геологоразведочные работы"
                        },
                        new
                        {
                            Id = -401,
                            ActivityFieldGroupId = -4,
                            Title = "Благоустройство и уборка территорий и зданий"
                        },
                        new
                        {
                            Id = -402,
                            ActivityFieldGroupId = -4,
                            Title = "Вентиляция и кондиционирование (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -403,
                            ActivityFieldGroupId = -4,
                            Title = "Водоснабжение и канализация"
                        },
                        new
                        {
                            Id = -404,
                            ActivityFieldGroupId = -4,
                            Title = "Лифтовое хозяйство (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -405,
                            ActivityFieldGroupId = -4,
                            Title = "Обеспечение пожарной безопасности, молниезащиты"
                        },
                        new
                        {
                            Id = -406,
                            ActivityFieldGroupId = -4,
                            Title = "Ремонт зданий и сооружений"
                        },
                        new
                        {
                            Id = -407,
                            ActivityFieldGroupId = -4,
                            Title = "Слаботочные сети (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -408,
                            ActivityFieldGroupId = -4,
                            Title = "Утилизация бытовых отходов"
                        },
                        new
                        {
                            Id = -409,
                            ActivityFieldGroupId = -4,
                            Title = "Энергоснабжение"
                        },
                        new
                        {
                            Id = -501,
                            ActivityFieldGroupId = -5,
                            Title = "Интернет-компания (поисковики, платежные системы, соц.сети, информационно-познавательные и развлекательные ресурсы, продвижение сайтов и прочее)"
                        },
                        new
                        {
                            Id = -502,
                            ActivityFieldGroupId = -5,
                            Title = "Интернет-провайдер"
                        },
                        new
                        {
                            Id = -503,
                            ActivityFieldGroupId = -5,
                            Title = "Разработка программного обеспечения"
                        },
                        new
                        {
                            Id = -504,
                            ActivityFieldGroupId = -5,
                            Title = "Системная интеграция, автоматизация технологических и бизнес-процессов предприятия, ИТ-консалтинг"
                        },
                        new
                        {
                            Id = -601,
                            ActivityFieldGroupId = -6,
                            Title = "Архив, библиотека, искусствоведение"
                        },
                        new
                        {
                            Id = -602,
                            ActivityFieldGroupId = -6,
                            Title = "Ботанический сад, зоопарк, заповедник"
                        },
                        new
                        {
                            Id = -603,
                            ActivityFieldGroupId = -6,
                            Title = "Музей, галерея, театр"
                        },
                        new
                        {
                            Id = -701,
                            ActivityFieldGroupId = -7,
                            Title = "Деревообработка (производство)"
                        },
                        new
                        {
                            Id = -702,
                            ActivityFieldGroupId = -7,
                            Title = "Продукция деревообработки (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -703,
                            ActivityFieldGroupId = -7,
                            Title = "Столярно-строительные изделия (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -704,
                            ActivityFieldGroupId = -7,
                            Title = "Столярно-строительные изделия (производство)"
                        },
                        new
                        {
                            Id = -705,
                            ActivityFieldGroupId = -7,
                            Title = "Целлюлозно-бумажная продукция (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -706,
                            ActivityFieldGroupId = -7,
                            Title = "Целлюлозно-бумажное производство"
                        },
                        new
                        {
                            Id = -801,
                            ActivityFieldGroupId = -8,
                            Title = "Аптека, оптика"
                        },
                        new
                        {
                            Id = -802,
                            ActivityFieldGroupId = -8,
                            Title = "Ветеринарная аптека"
                        },
                        new
                        {
                            Id = -803,
                            ActivityFieldGroupId = -8,
                            Title = "Ветеринарная деятельность"
                        },
                        new
                        {
                            Id = -804,
                            ActivityFieldGroupId = -8,
                            Title = "Клинические исследования"
                        },
                        new
                        {
                            Id = -805,
                            ActivityFieldGroupId = -8,
                            Title = "Лаборатория, исследовательский центр"
                        },
                        new
                        {
                            Id = -806,
                            ActivityFieldGroupId = -8,
                            Title = "Лечебно-профилактические учреждения"
                        },
                        new
                        {
                            Id = -807,
                            ActivityFieldGroupId = -8,
                            Title = "Учреждение соц.помощи и защиты"
                        },
                        new
                        {
                            Id = -808,
                            ActivityFieldGroupId = -8,
                            Title = "Фармацевтическая продукция (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -809,
                            ActivityFieldGroupId = -8,
                            Title = "Фармацевтическая продукция (производство)"
                        },
                        new
                        {
                            Id = -901,
                            ActivityFieldGroupId = -9,
                            Title = "Драгоценные, благородные и редкие металлы (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -902,
                            ActivityFieldGroupId = -9,
                            Title = "Драгоценные, благородные и редкие металлы (производство)"
                        },
                        new
                        {
                            Id = -903,
                            ActivityFieldGroupId = -9,
                            Title = "Металлические изделия, металлоконструкции (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -904,
                            ActivityFieldGroupId = -9,
                            Title = "Металлические изделия, металлоконструкции (производство)"
                        },
                        new
                        {
                            Id = -905,
                            ActivityFieldGroupId = -9,
                            Title = "Продукция цветной металлургии (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -906,
                            ActivityFieldGroupId = -9,
                            Title = "Продукция черной металлургии (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -907,
                            ActivityFieldGroupId = -9,
                            Title = "Цветная металлургия (выплавка, металлопрокат)"
                        },
                        new
                        {
                            Id = -908,
                            ActivityFieldGroupId = -9,
                            Title = "Черная металлургия (производство чугуна, стали, проката)"
                        },
                        new
                        {
                            Id = -1001,
                            ActivityFieldGroupId = -10,
                            Title = "ГСМ, топливо (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1002,
                            ActivityFieldGroupId = -10,
                            Title = "ГСМ, топливо (розничная торговля)"
                        },
                        new
                        {
                            Id = -1003,
                            ActivityFieldGroupId = -10,
                            Title = "Добыча газа"
                        },
                        new
                        {
                            Id = -1004,
                            ActivityFieldGroupId = -10,
                            Title = "Добыча нефти"
                        },
                        new
                        {
                            Id = -1005,
                            ActivityFieldGroupId = -10,
                            Title = "Нефтепереработка, нефтехимия (производство)"
                        },
                        new
                        {
                            Id = -1006,
                            ActivityFieldGroupId = -10,
                            Title = "Нефтехимия (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1007,
                            ActivityFieldGroupId = -10,
                            Title = "Переработка газа"
                        },
                        new
                        {
                            Id = -1008,
                            ActivityFieldGroupId = -10,
                            Title = "Транспортировка, хранение газа"
                        },
                        new
                        {
                            Id = -1009,
                            ActivityFieldGroupId = -10,
                            Title = "Транспортировка, хранение нефти"
                        },
                        new
                        {
                            Id = -1101,
                            ActivityFieldGroupId = -11,
                            Title = "Автошкола"
                        },
                        new
                        {
                            Id = -1102,
                            ActivityFieldGroupId = -11,
                            Title = "Бизнес-образование"
                        },
                        new
                        {
                            Id = -1103,
                            ActivityFieldGroupId = -11,
                            Title = "Вуз, ссуз колледж, ПТУ"
                        },
                        new
                        {
                            Id = -1104,
                            ActivityFieldGroupId = -11,
                            Title = "Интернат, детский дом"
                        },
                        new
                        {
                            Id = -1105,
                            ActivityFieldGroupId = -11,
                            Title = "Научно-исследовательская, научная, академическая деятельность"
                        },
                        new
                        {
                            Id = -1106,
                            ActivityFieldGroupId = -11,
                            Title = "Обучение иностранным языкам"
                        },
                        new
                        {
                            Id = -1107,
                            ActivityFieldGroupId = -11,
                            Title = "Обучение искусствам (рисование, пение, танцы, фото)"
                        },
                        new
                        {
                            Id = -1108,
                            ActivityFieldGroupId = -11,
                            Title = "Повышение квалификации, переквалификация"
                        },
                        new
                        {
                            Id = -1109,
                            ActivityFieldGroupId = -11,
                            Title = "Спортивное обучение"
                        },
                        new
                        {
                            Id = -1110,
                            ActivityFieldGroupId = -11,
                            Title = "Тренинговые компании"
                        },
                        new
                        {
                            Id = -1111,
                            ActivityFieldGroupId = -11,
                            Title = "Школа, детский сад"
                        },
                        new
                        {
                            Id = -1201,
                            ActivityFieldGroupId = -12,
                            Title = "Ассоциация в сфере культуры, искусства"
                        },
                        new
                        {
                            Id = -1202,
                            ActivityFieldGroupId = -12,
                            Title = "Благотворительная организация"
                        },
                        new
                        {
                            Id = -1203,
                            ActivityFieldGroupId = -12,
                            Title = "Общественная, политическая организация"
                        },
                        new
                        {
                            Id = -1204,
                            ActivityFieldGroupId = -12,
                            Title = "Профессиональная, предпринимательская организация"
                        },
                        new
                        {
                            Id = -1205,
                            ActivityFieldGroupId = -12,
                            Title = "Религиозная организация"
                        },
                        new
                        {
                            Id = -1206,
                            ActivityFieldGroupId = -12,
                            Title = "Спортивная федерация"
                        },
                        new
                        {
                            Id = -1207,
                            ActivityFieldGroupId = -12,
                            Title = "Фонд, грантодатель"
                        },
                        new
                        {
                            Id = -1301,
                            ActivityFieldGroupId = -13,
                            Title = "Авиаперевозки"
                        },
                        new
                        {
                            Id = -1302,
                            ActivityFieldGroupId = -13,
                            Title = "Автомобильные перевозки"
                        },
                        new
                        {
                            Id = -1303,
                            ActivityFieldGroupId = -13,
                            Title = "ВЭД, таможенное оформление"
                        },
                        new
                        {
                            Id = -1304,
                            ActivityFieldGroupId = -13,
                            Title = "Железнодорожные перевозки"
                        },
                        new
                        {
                            Id = -1305,
                            ActivityFieldGroupId = -13,
                            Title = "Курьерская, почтовая доставка"
                        },
                        new
                        {
                            Id = -1306,
                            ActivityFieldGroupId = -13,
                            Title = "Морские, речные перевозки"
                        },
                        new
                        {
                            Id = -1307,
                            ActivityFieldGroupId = -13,
                            Title = "Складские услуги"
                        },
                        new
                        {
                            Id = -1308,
                            ActivityFieldGroupId = -13,
                            Title = "Транспортно-логистические комплексы, порты (воздушный, водный, железнодорожный)"
                        },
                        new
                        {
                            Id = -1401,
                            ActivityFieldGroupId = -14,
                            Title = "Алкогольные напитки (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1402,
                            ActivityFieldGroupId = -14,
                            Title = "Безалкогольные напитки (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1403,
                            ActivityFieldGroupId = -14,
                            Title = "Безалкогольные напитки (производство)"
                        },
                        new
                        {
                            Id = -1404,
                            ActivityFieldGroupId = -14,
                            Title = "Вино (производство)"
                        },
                        new
                        {
                            Id = -1405,
                            ActivityFieldGroupId = -14,
                            Title = "Детское питание (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1406,
                            ActivityFieldGroupId = -14,
                            Title = "Детское питание (производство)"
                        },
                        new
                        {
                            Id = -1407,
                            ActivityFieldGroupId = -14,
                            Title = "Кондитерские изделия (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1408,
                            ActivityFieldGroupId = -14,
                            Title = "Кондитерские изделия (производство)"
                        },
                        new
                        {
                            Id = -1501,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для добывающей, энергетической, нефтегазовой и химической отрасли (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1502,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для добывающей, энергетической, нефтегазовой и химической отрасли (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1503,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для добывающей, энергетической, нефтегазовой и химической отрасли (производство)"
                        },
                        new
                        {
                            Id = -1504,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для металлургии и металлообработки (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1505,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для металлургии и металлообработки (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1506,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для металлургии и металлообработки (производство)"
                        },
                        new
                        {
                            Id = -1507,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для отраслей легкой промышленности (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1508,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для отраслей легкой промышленности (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1509,
                            ActivityFieldGroupId = -15,
                            Title = "Оборудование и станки для отраслей легкой промышленности (производство)"
                        },
                        new
                        {
                            Id = -1601,
                            ActivityFieldGroupId = -16,
                            Title = "Мобильная связь"
                        },
                        new
                        {
                            Id = -1602,
                            ActivityFieldGroupId = -16,
                            Title = "Оптоволоконная связь"
                        },
                        new
                        {
                            Id = -1603,
                            ActivityFieldGroupId = -16,
                            Title = "Спутниковая связь"
                        },
                        new
                        {
                            Id = -1604,
                            ActivityFieldGroupId = -16,
                            Title = "Фиксированная связь"
                        },
                        new
                        {
                            Id = -1701,
                            ActivityFieldGroupId = -17,
                            Title = "Аудит, управленческий учет, финансово-юридический консалтинг"
                        },
                        new
                        {
                            Id = -1702,
                            ActivityFieldGroupId = -17,
                            Title = "Банк"
                        },
                        new
                        {
                            Id = -1703,
                            ActivityFieldGroupId = -17,
                            Title = "Коллекторская деятельность"
                        },
                        new
                        {
                            Id = -1704,
                            ActivityFieldGroupId = -17,
                            Title = "Лизинговые компании"
                        },
                        new
                        {
                            Id = -1705,
                            ActivityFieldGroupId = -17,
                            Title = "НПФ"
                        },
                        new
                        {
                            Id = -1706,
                            ActivityFieldGroupId = -17,
                            Title = "Страхование, перестрахование"
                        },
                        new
                        {
                            Id = -1707,
                            ActivityFieldGroupId = -17,
                            Title = "Управляющая, инвестиционная компания (управление активами)"
                        },
                        new
                        {
                            Id = -1708,
                            ActivityFieldGroupId = -17,
                            Title = "Услуги по ведению бухгалтерского и налогового учета, расчет заработной платы"
                        },
                        new
                        {
                            Id = -1709,
                            ActivityFieldGroupId = -17,
                            Title = "Факторинговые компании"
                        },
                        new
                        {
                            Id = -1710,
                            ActivityFieldGroupId = -17,
                            Title = "Финансово-кредитное посредничество (биржа, брокерская деятельность, выпуск и обслуживание карт, оценка рисков, обменные пункты, агентства по кредитованию, инкассация, ломбард, платежные системы)"
                        },
                        new
                        {
                            Id = -1801,
                            ActivityFieldGroupId = -18,
                            Title = "Бытовая техника, электроника, климатическое оборудование (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1802,
                            ActivityFieldGroupId = -18,
                            Title = "Бытовая техника, электроника, климатическое оборудование (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1803,
                            ActivityFieldGroupId = -18,
                            Title = "Бытовая техника, электроника, климатическое оборудование (производство)"
                        },
                        new
                        {
                            Id = -1804,
                            ActivityFieldGroupId = -18,
                            Title = "Промышленное, бытовое электрооборудование и электротехника (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1805,
                            ActivityFieldGroupId = -18,
                            Title = "Промышленное, бытовое электрооборудование и электротехника (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1806,
                            ActivityFieldGroupId = -18,
                            Title = "Промышленное, бытовое электрооборудование и электротехника (производство)"
                        },
                        new
                        {
                            Id = -1807,
                            ActivityFieldGroupId = -18,
                            Title = "Электронно-вычислительная, оптическая, контрольно-измерительная техника, радиоэлектроника, автоматика (монтаж, сервис, ремонт)"
                        },
                        new
                        {
                            Id = -1808,
                            ActivityFieldGroupId = -18,
                            Title = "Электронно-вычислительная, оптическая, контрольно-измерительная техника, радиоэлектроника, автоматика (продвижение, оптовая торговля)"
                        },
                        new
                        {
                            Id = -1809,
                            ActivityFieldGroupId = -18,
                            Title = "Электронно-вычислительная, оптическая, контрольно-измерительная техника, радиоэлектроника, автоматика (производство)"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.ActivityFieldGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ActivityFieldGroups");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Title = "Гостиницы, рестораны, общепит, кейтеринг"
                        },
                        new
                        {
                            Id = -2,
                            Title = "Государственные организации"
                        },
                        new
                        {
                            Id = -3,
                            Title = "Добывающая отрасль"
                        },
                        new
                        {
                            Id = -4,
                            Title = "ЖКХ"
                        },
                        new
                        {
                            Id = -5,
                            Title = "Информационные технологии, системная интеграция, интернет"
                        },
                        new
                        {
                            Id = -6,
                            Title = "Искусство, культура"
                        },
                        new
                        {
                            Id = -7,
                            Title = "Лесная промышленность, деревообработка"
                        },
                        new
                        {
                            Id = -8,
                            Title = "Медицина, фармацевтика, аптеки"
                        },
                        new
                        {
                            Id = -9,
                            Title = "Металлургия, металлообработка"
                        },
                        new
                        {
                            Id = -10,
                            Title = "Нефть и газ"
                        },
                        new
                        {
                            Id = -11,
                            Title = "Образовательные учреждения"
                        },
                        new
                        {
                            Id = -12,
                            Title = "Общественная деятельность, партии, благотворительность, НКО"
                        },
                        new
                        {
                            Id = -13,
                            Title = "Перевозки, логистика, склад, ВЭД"
                        },
                        new
                        {
                            Id = -14,
                            Title = "Продукты питания"
                        },
                        new
                        {
                            Id = -15,
                            Title = "Промышленное оборудование, техника, станки и комплектующие"
                        },
                        new
                        {
                            Id = -16,
                            Title = "Телекоммуникации, связь"
                        },
                        new
                        {
                            Id = -17,
                            Title = "Финансовый сектор"
                        },
                        new
                        {
                            Id = -18,
                            Title = "Электроника, приборостроение, бытовая техника, компьютеры и оргтехника"
                        },
                        new
                        {
                            Id = -19,
                            Title = "Автомобильный бизнес"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Curator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UX_Curator_Email")
                        .IsUnique();

                    b.ToTable("Curators");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Email = "admin@launchpad.ru",
                            FirstName = "Администратор",
                            IsAdmin = true,
                            LastName = "",
                            MiddleName = "",
                            PasswordHash = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Среднее"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Среднее специальное"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Неоконченное высшее"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Высшее"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Бакалавр"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Магистр"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Доктор наук"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool?>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Biography = "Специализируюсь на экосистеме React: TypeScript, Redux Toolkit, Next.js. За это время успел поработать как над крупными корпоративными проектами (CRM, панели администратора), так и над высоконагруженными публичными сервисами.\n\nОсновной фокус: построение компонентной архитектуры, рефакторинг легаси, внедрение SSR (Next.js) и настройка сборки (Webpack/Vite). Имею опыт наставничества джуниоров и проведения технических интервью. Ищу компанию с прозрачными процессами и современным технологическим стеком, где могу приносить пользу и развиваться дальше.",
                            Email = "kadet_2003@list.ru",
                            FirstName = "Артём",
                            LastName = "Терешков",
                            MiddleName = "Вячеславович",
                            PasswordHash = "0D73C0A5D54B086B544B1A76A121CAE545B6A204F6D85E4CB68A0786991FEC67",
                            RegisteredOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletionYear")
                        .HasColumnType("integer");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CompletionYear = 2024,
                            EducationLevelId = 6,
                            EmployeeId = -1L,
                            Faculty = "Факультет информационных технологий",
                            Organization = "МФТИ",
                            Specialization = "Веб-разработка"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeProjects");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            DateFrom = new DateOnly(2026, 3, 15),
                            DateTo = new DateOnly(2026, 3, 30),
                            Description = "Карьерный аггрегатор для студентов",
                            EmployeeId = -1L,
                            Specialization = "React Frontend Developer",
                            Title = "Трамплин"
                        },
                        new
                        {
                            Id = -2L,
                            DateFrom = new DateOnly(2024, 6, 1),
                            DateTo = new DateOnly(2024, 9, 1),
                            Description = "Инструмент учета финансов",
                            EmployeeId = -1L,
                            Specialization = "React Frontend Developer",
                            Title = "Finance Helper"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CompanyName = "Трамплин",
                            Description = "Платформа «Трамплин» должна стать экосистемой, где студенты не просто ищут работу, а строят карьеру с нуля: находят менторов, участвуют в карьерных мероприятиях компаний и получают предложения о стажировках, основываясь на своих навыках и активности. Некоторые функциональные и нефункциональные требования описаны заказчиком напрямую, по другим же функциональным и нефункциональным требованиям вам необходимо выработать решения самостоятельно и аргументировать их перед заказчиком",
                            Email = "kadet_2003@list.ru",
                            PasswordHash = "0D73C0A5D54B086B544B1A76A121CAE545B6A204F6D85E4CB68A0786991FEC67",
                            RegisteredOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EmployerId")
                        .HasColumnType("bigint");

                    b.Property<int>("EmployerVerificationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("SocialNetworkLink")
                        .HasColumnType("varchar(256)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxpayerIndividualNumber")
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.HasIndex("EmployerVerificationTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("EmployerVerifications");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EmployerVerificationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "На рассмотрении"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Отказано"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Требуются уточнения"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Подтверждено"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerificationType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EmployerVerificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HtmlDescription = "<p>Отправьте один из документов:</p>\r\n<ul>\r\n  <li>Свидетельство о государственной регистрации ЮЛ/ИП</li>\r\n  <li>Свидетельство о постановке на налоговый учёт ЮЛ/ИП</li>\r\n  <li>Лист записи ЕГРЮЛ/ЕГРИП, его можно получить в личном кабинете на <a href=\"https://nalog.gov.ru\">nalog.gov.ru</a></li>\r\n</ul>",
                            Title = "Организация"
                        },
                        new
                        {
                            Id = 2,
                            HtmlDescription = "<p>Отправьте один из документов:</p>\r\n<ul>\r\n  <li>Свидетельство о государственной регистрации ЮЛ/ИП</li>\r\n  <li>Свидетельство о постановке на налоговый учёт ЮЛ/ИП</li>\r\n  <li>Лист записи ЕГРЮЛ/ЕГРИП, его можно получить в личном кабинете на <a href=\"https://nalog.gov.ru\">nalog.gov.ru</a></li>\r\n</ul>",
                            Title = "Кадровое агентство"
                        },
                        new
                        {
                            Id = 3,
                            HtmlDescription = "<p>Загрузите фото или скан листа записи ЕГРЮЛ или ЕГРИП о создании юрлица или регистрации ИП</p>",
                            Title = "Проект"
                        },
                        new
                        {
                            Id = 4,
                            HtmlDescription = "Загрузите скан или фото первого разворота паспорта",
                            Title = "Частное лицо"
                        },
                        new
                        {
                            Id = 5,
                            HtmlDescription = "<p>Отправьте один из документов:</p>\r\n<ul>\r\n  <li>Разворот паспорта с фотографией</li>\r\n  <li>Фото или скан справки о регистрации плательщика НПД</li>\r\n</ul>",
                            Title = "Самозанятый"
                        },
                        new
                        {
                            Id = 6,
                            HtmlDescription = "<p>Отправьте один из документов:</p>\r\n<ul>\r\n  <li>Разворот паспорта с фотографией</li>\r\n  <li>Фото или скан справки о регистрации плательщика НПД</li>\r\n</ul>",
                            Title = "Кадровое агентство"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystemTag")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsSystemTag = true,
                            Title = "React"
                        },
                        new
                        {
                            Id = -2,
                            IsSystemTag = true,
                            Title = ".NET"
                        },
                        new
                        {
                            Id = -3,
                            IsSystemTag = true,
                            Title = "Git"
                        },
                        new
                        {
                            Id = -4,
                            IsSystemTag = true,
                            Title = "HTML"
                        },
                        new
                        {
                            Id = -5,
                            IsSystemTag = true,
                            Title = "CSS"
                        },
                        new
                        {
                            Id = -6,
                            IsSystemTag = true,
                            Title = "SOLID"
                        },
                        new
                        {
                            Id = -7,
                            IsSystemTag = true,
                            Title = "Entity framework core"
                        });
                });

            modelBuilder.Entity("ActivityFieldEmployer", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.ActivityField", null)
                        .WithMany()
                        .HasForeignKey("ActivityFieldsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launchpad.Domain.Entities.Employer", null)
                        .WithMany()
                        .HasForeignKey("EmployersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launchpad.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.ActivityField", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.ActivityFieldGroup", "ActivityFieldGroup")
                        .WithMany("ActivityFields")
                        .HasForeignKey("ActivityFieldGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityFieldGroup_ActivityFields");

                    b.Navigation("ActivityFieldGroup");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EducationLevel_EmployeeEducations");

                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeEducations");

                    b.Navigation("EducationLevel");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeProjects");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerification", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employer", "Employer")
                        .WithOne("Verification")
                        .HasForeignKey("Launchpad.Domain.Entities.EmployerVerification", "EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employer_Verification");

                    b.HasOne("Launchpad.Domain.Entities.EmployerVerificationType", "Type")
                        .WithMany("EmployerVerifications")
                        .HasForeignKey("EmployerVerificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployerVerifications_EmployerVerificationType");

                    b.HasOne("Launchpad.Domain.Entities.EmployerVerificationStatus", "Status")
                        .WithMany("EmployerVerifications")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmployerVerificationStatus_EmployerVerifications");

                    b.Navigation("Employer");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.ActivityFieldGroup", b =>
                {
                    b.Navigation("ActivityFields");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("EmployeeEducations");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeEducations");

                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employer", b =>
                {
                    b.Navigation("Verification");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerificationStatus", b =>
                {
                    b.Navigation("EmployerVerifications");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployerVerificationType", b =>
                {
                    b.Navigation("EmployerVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
