// <auto-generated />
using System;
using Launchpad.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Launchpad.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319102236_AddedBirthDateEmployee")]
    partial class AddedBirthDateEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.Property<long>("EmployeesId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("EmployeeSkillMap", (string)null);
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Среднее"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Среднее специальное"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Неоконченное высшее"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Высшее"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Бакалавр"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Магистр"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Кандидат наук"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Доктор наук"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool?>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Biography = "Специализируюсь на экосистеме React: TypeScript, Redux Toolkit, Next.js. За это время успел поработать как над крупными корпоративными проектами (CRM, панели администратора), так и над высоконагруженными публичными сервисами.\n\nОсновной фокус: построение компонентной архитектуры, рефакторинг легаси, внедрение SSR (Next.js) и настройка сборки (Webpack/Vite). Имею опыт наставничества джуниоров и проведения технических интервью. Ищу компанию с прозрачными процессами и современным технологическим стеком, где могу приносить пользу и развиваться дальше.",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kadet_2003@list.ru",
                            FirstName = "Артём",
                            LastName = "Терешков",
                            MiddleName = "Вячеславович",
                            PasswordHash = "0D73C0A5D54B086B544B1A76A121CAE545B6A204F6D85E4CB68A0786991FEC67",
                            RegisteredOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletionYear")
                        .HasColumnType("integer");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CompletionYear = 2024,
                            EducationLevelId = 6,
                            EmployeeId = -1L,
                            Faculty = "Факультет информационных технологий",
                            Organization = "МФТИ",
                            Specialization = "Веб-разработка"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeProjects");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            DateFrom = new DateOnly(2026, 3, 15),
                            DateTo = new DateOnly(2026, 3, 30),
                            Description = "Карьерный аггрегатор для студентов",
                            EmployeeId = -1L,
                            Specialization = "React Frontend Developer",
                            Title = "Трамплин"
                        },
                        new
                        {
                            Id = -2L,
                            DateFrom = new DateOnly(2024, 6, 1),
                            DateTo = new DateOnly(2024, 9, 1),
                            Description = "Инструмент учета финансов",
                            EmployeeId = -1L,
                            Specialization = "React Frontend Developer",
                            Title = "Finance Helper"
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CompanyName = "Трамплин",
                            Description = "Платформа «Трамплин» должна стать экосистемой, где студенты не просто ищут работу, а строят карьеру с нуля: находят менторов, участвуют в карьерных мероприятиях компаний и получают предложения о стажировках, основываясь на своих навыках и активности. Некоторые функциональные и нефункциональные требования описаны заказчиком напрямую, по другим же функциональным и нефункциональным требованиям вам необходимо выработать решения самостоятельно и аргументировать их перед заказчиком",
                            Email = "kadet_2003@list.ru",
                            PasswordHash = "0D73C0A5D54B086B544B1A76A121CAE545B6A204F6D85E4CB68A0786991FEC67",
                            RegisteredOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystemTag")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsSystemTag = true,
                            Title = "React"
                        },
                        new
                        {
                            Id = -2,
                            IsSystemTag = true,
                            Title = ".NET"
                        },
                        new
                        {
                            Id = -3,
                            IsSystemTag = true,
                            Title = "Git"
                        },
                        new
                        {
                            Id = -4,
                            IsSystemTag = true,
                            Title = "HTML"
                        },
                        new
                        {
                            Id = -5,
                            IsSystemTag = true,
                            Title = "CSS"
                        },
                        new
                        {
                            Id = -6,
                            IsSystemTag = true,
                            Title = "SOLID"
                        },
                        new
                        {
                            Id = -7,
                            IsSystemTag = true,
                            Title = "Entity framework core"
                        });
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Launchpad.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeEducation", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.EducationLevel", "EducationLevel")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EducationLevel_EmployeeEducations");

                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeEducations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeEducations");

                    b.Navigation("EducationLevel");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EmployeeProject", b =>
                {
                    b.HasOne("Launchpad.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeProjects");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.EducationLevel", b =>
                {
                    b.Navigation("EmployeeEducations");
                });

            modelBuilder.Entity("Launchpad.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeEducations");

                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
