# docker compose -p launchpad up -d --build --force-recreate
# docker run --rm --network launchpad-network alpine/curl http://launchpad.keycloak:9000/health/ready

services:        
  candidates.api:
    image: launchpad.candidates.api
    container_name: launchpad.candidates.api
    profiles: ["all", "load-test"]
    ports:
      - "3333:8080"
    build:
      context: Launchpad.Candidates/
      dockerfile: Launchpad.Candidates.Api/Dockerfile
      no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings:SqlDatabase=${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - launchpad-network
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/localhost/8080 && 
        printf "GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && 
        cat <&3' | grep -q "200 OK"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  database:
    image: postgis/postgis:15-3.5-alpine
    container_name: launchpad.database
    restart: unless-stopped
    profiles: ["all", "load-test"]
    ports:
      - "1300:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - .infrastructure/database:/docker-entrypoint-initdb.d:ro
      - launchpad-database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d launchpad_candidates" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - launchpad-network
  
  database.metrics:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: launchpad.database.metrics
    profiles: ["all", "load-test"]
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "9180:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@database:5432?sslmode=disable"
    networks:
      - launchpad-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: launchpad.keycloak
    restart: unless-stopped
    profiles: ["all"]
    depends_on:
      database:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
    ports:
      - "1200:8080"
      - "1250:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_IMPORT=/opt/keycloak/data/import/launchpad-realm-export.json
    
      # Management setup
      - KC_HTTP_MANAGEMENT_PORT=9000
      - KC_METRICS_ENABLED=true
      - KC_EVENT_METRICS_USER_ENABLED=true
      - KC_HEALTH_ENABLED=true

      # Database setup
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=admin
      - KC_DB_SCHEMA=public
    volumes:
      - launchpad-keycloak-data:/opt/keycloak/data
      - .infrastructure/keycloak/themes:/opt/keycloak/themes:ro
      - .infrastructure/keycloak/data:/opt/keycloak/data/import:ro
    networks:
      - launchpad-network
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/localhost/9000 && 
        printf "GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && 
        cat <&3' | grep -q "\"status\": \"UP\""
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
  prometheus:
    image: prom/prometheus:latest
    container_name: launchpad.prometheus
    restart: unless-stopped
    profiles: ["all", "load-test"]
    ports:
      - "9080:9090"
    volumes:
      - launchpad-metrics-data:/prometheus
      - .infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - launchpad-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: launchpad.grafana
    profiles: ["all", "load-test"]
    ports:
      - "3240:3000"
    volumes:
      - .infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - .infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - launchpad-metrics-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - launchpad-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  
  k6:
    image: grafana/k6:latest
    container_name: launchpad.k6
    profiles: ["load-test"]
    volumes:
      - .infrastructure/monitoring/load-test/script.js:/script.js
    environment:
      - CANDIDATES_API_URL=http://launchpad.candidates.api:8080
    command: run /script.js
    networks:
      - launchpad-network
    depends_on:
      candidates.api:
        condition: service_healthy
  
  elasticsearch:
    image: elasticsearch:9.3.2
    container_name: launchpad.elasricsearch
    restart: unless-stopped
    profiles: ["all", "load-test"]
    ports:
      - "9228:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - launchpad-elastic-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:9.3.2
    container_name: launchpad.logstash
    restart: unless-stopped
    profiles: ["all", "load-test"]
    ports:
      - "5049:5044"
    environment:
      - ES_HOST=http://elasticsearch:9200
    volumes:
      - .infrastructure/elastic/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:9.3.2
    container_name: launchpad.kibana
    profiles: ["all", "load-test"]
    ports:
      - "5609:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:5601/api/status" ]
      interval: 5s
      timeout: 5s
      retries: 10
      
  kafka:
    image: confluentinc/cp-kafka:7.7.8
    container_name: launchpad.kafka
    profiles: ["all", "load-test"]
    ports:
      - "9099:9099"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@launchpad.kafka:29093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://launchpad.kafka:9092,EXTERNAL://localhost:9099'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qz'
    volumes:
      - launchpad-kafka-data:/var/lib/kafka/data
      - ./kafka/init-kafka.sh:/usr/bin/init-kafka.sh
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: [ "/bin/sh", "-c", "/usr/bin/init-kafka.sh & /etc/confluent/docker/run" ]
    networks:
      - launchpad-network

volumes:
  launchpad-keycloak-data:
    name: launchpad-keycloak-data
  launchpad-metrics-data:
    name: launchpad-metrics-data
  launchpad-database-data:
    name: launchpad-database-data
  launchpad-elastic-data:
    name: launchpad-elastic-data
  launchpad-kafka-data:
    name: launchpad-kafka-data

networks:
  launchpad-network:
    driver: bridge
    name: launchpad-network