# docker compose -p launchpad up -d --build --force-recreate
# docker run --rm --network launchpad-network alpine/curl http://launchpad.keycloak:8080/realms/Launchpad/.well-known/openid-configuration
# docker run --rm --network launchpad-network alpine/curl http://launchpad.keycloak:8080/health/live

services:        
  candidates.api:
    image: launchpad.candidates.api
    container_name: launchpad.candidates.api
    ports:
      - "3333:8080"
    build:
      context: Launchpad.Candidates/
      dockerfile: Launchpad.Candidates.Api/Dockerfile
      no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      database:
        condition: service_healthy
    networks:
      - launchpad-network

  database:
    image: postgis/postgis:15-3.5-alpine
    container_name: launchpad.database
    restart: unless-stopped
    ports:
      - "1300:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - .infrastructure/database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d launchpad_candidates" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - launchpad-network

  keycloack:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: launchpad.keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    ports:
      - "1200:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_IMPORT=/opt/keycloak/data/import/launchpad-realm-export.json
      - KC_HEALTH_ENABLED=true

      # Database setup
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_DB_SCHEMA=public
    volumes:
      - launchpad-keycloak-data:/opt/keycloak/data
      - .infrastructure/keycloak/themes:/opt/keycloak/themes:ro
      - .infrastructure/keycloak/data:/opt/keycloak/data/import:ro
    networks:
      - launchpad-network
    
  prometheus:
    image: prom/prometheus:latest
    container_name: launchpad.prometheus
    restart: unless-stopped
    ports:
      - "9080:9090"
    volumes:
      - .infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - launchpad-network

  grafana:
    image: grafana/grafana:latest
    container_name: launchpad.grafana
    ports:
      - "3240:3000"
    volumes:
      - .infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - .infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - launchpad-network

volumes:
  launchpad-keycloak-data:

networks:
  launchpad-network:
    driver: bridge
    name: launchpad-network