input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if ![ServiceName] {
    mutate {
      add_field => { "ServiceName" => "unknown" }
    }
  }

  mutate {
    uppercase => ["level"]
  }
}

output {
  elasticsearch {
    hosts => ["${ES_HOST}"]
    index => "launchpad-%{ServiceName}-%{+YYYY.MM.dd}"
    user => elastic
    password => admin
  }
  
  # For debuging only
  stdout { codec => rubydebug }
}