# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Launchpad/Launchpad.slnx

      - name: Build
        run: dotnet build --no-restore src/Launchpad/Launchpad.slnx --configuration Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            src/**/bin/
            src/**/obj/
          retention-days: 1
        
  unit-test-api:
    needs: build-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Unit test
        run: dotnet test --configuration Release --no-build --verbosity normal --filter Category=Unit src/Launchpad/Launchpad.slnx

  integration-test-api:
    needs: build-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Integration test
        run: dotnet test --configuration Release --no-build --verbosity normal --filter Category=Integration src/Launchpad/Launchpad.slnx