name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-obsolete-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Launchpad/Launchpad.slnx

      - name: Build
        run: dotnet build --no-restore src/Launchpad/Launchpad.slnx --configuration Release

  build-and-test-candidates-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/Launchpad.Candidates/Launchpad.Candidates.slnx

      - name: Build
        run: dotnet build --no-restore src/Launchpad.Candidates/Launchpad.Candidates.slnx --configuration Release

#      - name: Unit test
#        run: dotnet test --configuration Release --no-build --verbosity normal --filter Category=Unit src/Launchpad.Candidates/Launchpad.Candidates.slnx
#
#      - name: Integration test
#        run: dotnet test --configuration Release --no-build --verbosity normal --filter Category=Integration src/Launchpad.Candidates/Launchpad.Candidates.slnx